config/routes.rb
Rails.application.routes.draw do

  # always declare root path(s) first
  authenticated :user do
    root 'welcome#index', as: :authenticated_root
  end
  root to: 'high_voltage/pages#show', id: 'index'
  get '/index', to: redirect('/')

  resources :relationships
  resources :vendor_accounts
  resources :vendors
  devise_for :users, controllers: { registrations: 'registrations', confirmations: 'confirmations', passwords: 'passwords', sessions: 'sessions',
                                    unlocks: 'unlocks' }, :path => 'users', :path_names => { :sign_up => 'sign_up_form' }

  devise_scope :user do
    get 'users/password/create_new_invitation/:uuid', to: 'passwords#create_new_invitation', as: :create_new_password_invitation
    match 'active' => 'sessions#active', via: :get
    match 'timeout' => 'sessions#timeout', via: :get
  end

  scope 'insurance' do
    resources :lives, controller: :life_and_disabilities
    resources :properties, controller: :property_and_casualties
    resources :healths
  end

  delete 'insurance/properties/provider/:id' => 'property_and_casualties#destroy_provider'
  delete 'insurance/healths/provider/:id' => 'healths#destroy_provider'
  delete 'insurance/lives/provider/:id' => 'life_and_disabilities#destroy_provider'

  # Insurance Update All
  post 'insurance/lives/update_all' => 'life_and_disabilities#update_all'
  post 'insurance/healths/update_all' => 'healths#update_all'
  post 'insurance/properties/update_all' => 'property_and_casualties#update_all'

  # Mailer
  post 'contact_us', to: 'messages#create'
  post 'mailing_list', to: 'interested_users#create'
  post 'users/sign_up_form', as: :sign_up

  # Taxes
  resources :taxes
  post 'taxes/update_tax_preparers', to: 'taxes#update_tax_preparers', as: :tax_update_preparers
  
  # Final Wishes
  resources :final_wishes

  get 'files' => 'welcome#files'
  get 'cards' => 'welcome#cards'
  get 'cardcolumn' => 'welcome#cardcolumn'
  get 'thank_you' => 'welcome#thank_you'
  get 'email_confirmed' => 'welcome#email_confirmed'
  get 'password_link_expired(/:corporate)' => 'welcome#reset_password_expired', as: :password_link_expired
  get 'onboarding_back' => 'welcome#onboarding_back', as: :onboarding_back

  # Default category pages ?Could probably be done better programatically?
  get 'wills_powers_of_attorney' => 'categories#wills_powers_of_attorney'
  get 'trusts_entities' => 'categories#trusts_entities'
  get 'healthcare_choices' => 'categories#healthcare_choices'
  get 'insurance' => 'categories#insurance', as: 'insurance'
  get 'shared' => 'categories#shared'
  get 'shared_view' => 'categories#shared_view_dashboard'
  get 'web_accounts' => 'categories#web_accounts'

  resources :interested_users
  get 'mailing_list_confirm' => 'interested_users#mailing_list_confirm'

  resources :users, only: [:index, :destroy]

  # Wills
  get 'wills/new(/:shared_user_id)', to: 'wills#new', as: :new_will
  get 'wills/edit/:id(/:shared_user_id)', to: 'wills#edit', as: :edit_will
  get 'wills/show/:id(/:shared_user_id)', to: 'wills#show', as: :will
  patch 'wills/show/:id', to: 'wills#update'
  patch 'wills/:id', to: 'wills#update'
  get 'wills', to: 'wills#index', as: :wills
  post 'wills', to: 'wills#create'
  put 'wills', to: 'wills#update'
  delete 'wills/:id', to: 'wills#destroy'

  # Powers of Attorney
  get 'power_of_attorneys/new(/:shared_user_id)', to: 'power_of_attorneys#new', as: :new_power_of_attorney
  get 'power_of_attorneys/edit/:id(/:shared_user_id)', to: 'power_of_attorneys#edit', as: :edit_power_of_attorney
  get 'power_of_attorneys/show/:id(/:shared_user_id)', to: 'power_of_attorneys#show', as: :power_of_attorney
  patch 'power_of_attorneys/show/:id', to: 'power_of_attorneys#update'
  patch 'power_of_attorneys/:id', to: 'power_of_attorneys#update'
  get 'power_of_attorneys', to: 'power_of_attorneys#index', as: :power_of_attorneys
  post 'power_of_attorneys', to: 'power_of_attorneys#create'
  put 'power_of_attorneys', to: 'power_of_attorneys#update'
  delete 'power_of_attorneys/:id', to: 'power_of_attorneys#destroy'
  delete 'power_of_attorneys/powers_of_attorney_contact/:id', to: 'power_of_attorneys#destroy_power_of_attorney_contact', as: :delete_power_of_attorney
  get 'power_of_attorneys/new/get_powers_of_attorney_details', to: 'power_of_attorneys#get_powers_of_attorney_details'

  # Trusts
  get 'trusts/new(/:shared_user_id)', to: 'trusts#new', as: :new_trust
  get 'trusts/edit/:id(/:shared_user_id)', to: 'trusts#edit', as: :edit_trust
  get 'trusts/show/:id(/:shared_user_id)', to: 'trusts#show', as: :trust
  patch 'trusts/show/:id', to: 'trusts#update'
  patch 'trusts/:id', to: 'trusts#update'
  get 'trusts', to: 'trusts#index', as: :trusts
  post 'trusts', to: 'trusts#create'
  post 'trusts/update_all', to: 'trusts#update_all'
  put 'trusts', to: 'trusts#update'
  delete 'trusts/:id', to: 'trusts#destroy'

  # Entities
  get 'entities/new(/:shared_user_id)', to: 'entities#new', as: :new_entity
  get 'entities/:id/edit(/:shared_user_id)', to: 'entities#edit', as: :edit_entity
  patch 'entities/:id', to: 'entities#update'
  get 'entities/:id(/:shared_user_id)', to: 'entities#show', as: :entity
  post 'entities', to: 'entities#create', as: :entities
  post 'entities/update_all', to: 'entities#update_all'
  delete 'entities/:id', to: 'entities#destroy'

  resources :categories do
    member do
      post :share
      get :share_category
      delete 'share_category/:contact_id', to: 'categories#destroy_share_category'
    end
  end
  
  # Online Accounts
  get 'online_accounts/reveal_password/:account_id(/:shared_user_id)', to: 'online_accounts#reveal_password'
  get 'online_accounts', to: 'online_accounts#index', as: :online_accounts
  get 'online_accounts/new(/:shared_user_id)', to: 'online_accounts#new', as: :new_online_account
  get 'online_accounts/:id/edit(/:shared_user_id)', to: 'online_accounts#edit', as: :edit_online_account
  patch 'online_accounts/:id', to: 'online_accounts#update', as: :online_account
  post 'online_accounts', to: 'online_accounts#create'
  post 'online_accounts/update_all', to: 'online_accounts#update_all'
  delete 'online_accounts/:id', to: 'online_accounts#destroy'

  # Contacts
  get 'contacts/relationship_values/:contact_type(/:shared_user_id)', to: 'contacts#relationship_values'
  get 'contacts/new(/:shared_user_id)', to: 'contacts#new', as: :new_contact
  get 'contacts/:id(/:shared_user_id)', to: 'contacts#show', as: :contact
  get 'contacts/:id/edit(/:shared_user_id)', to: 'contacts#edit', as: :edit_contact
  resources :contacts, except: [:new, :edit, :show]

  # insurance details and create new account routes
  get 'insurance/:group/new_account', to: 'categories#new_account', as: :new_account_category
  get 'insurance/:group/details', to: 'categories#details_account', as: :details_account_category

  # Shares
  get 'shares' => 'shares#index'
  get 'shares/expired/:shared_user_id' => 'shares#shared_user_expired', as: :shared_user_expired

  # Documents
  get 'documents/get_drop_down_options/:category(/:shared_user_id)', to: 'documents#get_drop_down_options'
  get 'documents/get_card_names/:category(/:shared_user_id)', to: 'documents#get_card_names'
  get 'documents/document_category_share_contacts/:category(/:shared_user_id)', to: 'documents#document_category_share_contacts'
  get 'documents/document_subcategory_share_contacts/:category/:subcategory(/:shared_user_id)', to: 'documents#document_subcategory_share_contacts'
  get 'documents/', to: 'documents#index', as: :documents
  post 'documents/', to: 'documents#create'
  get 'documents/new(/:shared_user_id)', to: 'documents#new', as: :new_document
  get 'documents/edit/:uuid(/:shared_user_id)', to: 'documents#edit', as: :edit_document
  get 'documents/:uuid', to: 'documents#show', as: :document
  patch 'documents/:uuid', to: 'documents#update'
  delete 'documents/:uuid', to: 'documents#destroy'
  get 'documents/download/:uuid(/:shared_user_id)', to: 'documents#download', as: :download_document
  get 'documents/preview/:uuid(/:shared_user_id)', to: 'documents#preview', as: :preview_document
  get 'shared_view/:shared_user_id/documents/:uuid', to: 'documents#show', as: :shared_view_document
  post 'documents/mass_document_upload(/:shared_user_id)', to: 'documents#mass_document_upload', as: :mass_document_upload
  resources :documents, except: [:new, :edit], param: :uuid

  # Account Settings
  get 'account_settings', to: 'account_settings#index', as: :account_settings
  get 'account_settings/remove_corporate_access/:contact_id', to: 'account_settings#remove_corporate_access', as: :remove_corporate_access_account_settings
  get 'account_settings/remove_corporate_payment', to: 'account_settings#remove_corporate_payment', as: :remove_corporate_payment_account_settings
  get 'account_settings/vault_co_owners', to: 'account_settings#vault_co_owners', as: :vault_co_owners_account_settings
  get 'account_settings/login_settings', to: 'account_settings#login_settings', as: :login_settings_account_settings
  get 'account_settings/manage_subscription', to: 'account_settings#manage_subscription', as: :manage_subscription_account_settings
  get 'account_settings/vault_inheritance', to: 'account_settings#vault_inheritance', as: :vault_inheritance_account_settings
  get 'account_settings/phone_setup', to: 'account_settings#phone_setup', as: :phone_setup_account_settings
  put 'account_settings/phone_setup_update', to: 'account_settings#phone_setup_update', as: :phone_update_account_settings
  get 'account_settings/billing_info', to: 'account_settings#billing_info', as: :billing_info_account_settings
  get 'account_settings/cancel_subscription', to: 'account_settings#cancel_subscription', as: :cancel_subscription_account_settings
  get 'account_settings/invoice_information/:id', to: 'account_settings#invoice_information', as: :invoice_information_account_settings

app/helpers/account_settings_helper.rb
module AccountSettingsHelper
  def cvv_code_image
    asset_url('cvv_code.png')
  end
  
  def always_mfa_phone_text
    return '(mandatory for corporate accounts)' if current_user.present? &&
                                                   corporate?
    '(recommended)'
  end
  
  def mfa_options_classes
    return " opacity-half pl-0 " if current_user.present? && corporate?
    " pl-0 "
  end
end

app/views/account_settings/_free_trial_subscription_info.html.erb
<label>Plan</label>
<p>Free Trial - <%= trial.active? ? 'Active' : 'Expired' %></p>

<label>Trial Start Date</label>
<p><%= date_format(trial.start_at) || '–' %></p>

<label>Trial End Date</label>
<p><%= date_format(trial.end_at) || '–' %></p>

<div class="mt-30">
  <%= link_to "Upgrade", billing_info_account_settings_path, class: "button primary-button big-button" %>
</div>

app/views/account_settings/_login_settings.html.erb
<%= form_for @user_profile, :url => url_for(action: :update_login_settings, controller: :account_settings) do |f| %>
  <div class="card b-radius-0 b-none box-shadow-none">
    <% if @user_profile.errors.any? %>
      <% errors = true %>
    <% end %>
    <h3>Two-Factor Authentication</h3>

    <%= f.label :two_factor_phone_number, 'Cell Phone Number' %>
    <p id="two_factor_phone_label"><%= f.object.two_factor_phone_number %></p>

    <p class="mb-30">
      <%= link_to 'Change Two-Factor Phone Number', phone_setup_account_settings_path, class: "button secondary-button small-button", id: "change-phone-btn"%>
    </p>

    <%= f.label :mfa_frequency, "Login Settings" %>
    <ul class="radio-list mb-30">
      <li class="radio-list">
        <%= radio_button_tag "user_profile[mfa_frequency]", "always", radio_button_checked?("always", @user_profile.mfa_frequency) || corporate? %>
        <label for="user_profile_mfa_frequency_always">Verify login using my phone every time<span class="recommended"><%= always_mfa_phone_text %></span></label>
        <div class="check"></div>
      </li>
      <li class="radio-list">
        <%= radio_button_tag "user_profile[mfa_frequency]", "new_ip", radio_button_checked?("new_ip", @user_profile.mfa_frequency) && !corporate?, disabled: corporate? %>
        <label for="user_profile_mfa_frequency_new_ip"><div class="inline <%= mfa_options_classes %>">Verify login using my phone when logging in from a new device</div></label>
        <div class="check"></div>
      </li>
      <li class="radio-list">
        <%= radio_button_tag "user_profile[mfa_frequency]", "never", radio_button_checked?("never", @user_profile.mfa_frequency) && !corporate?, disabled: corporate? %>
        <label for="user_profile_mfa_frequency_never"><div class="inline <%= mfa_options_classes %>">Do not use my phone for login</div></label>
        <div class="check"></div>
      </li>
    </ul>

    <h3>Password</h3>
    <%= f.label :password, 'Update Password' %>
    <% if errors && @user_profile.errors.messages[:password].present? %>
      <span class="error-label"> - <%= @user_profile.errors.messages[:password].first %></span>
    <% end %>
    <%= f.password_field :password, {autocomplete: "off", class: ("input-error" if @user_profile.errors.messages[:password].present?) } %>
    <%= render partial: 'layouts/password_requirements', locals: { password_field_id: 'user_profile_password' } %>

    <%= f.label :password_confirmation, 'Confirm Password' %>
    <% if errors && @user_profile.errors.messages[:password_confirmation].present? %>
      <span class="error-label"> - <%= @user_profile.errors.messages[:password_confirmation].first %></span>
    <% end %>
    <%= f.password_field :password_confirmation, {autocomplete: "off", class: ("input-error" if @user_profile.errors.messages[:password_confirmation].present?) } %>
    
  </div>
  
  <div class="ml-15 mb-30">
    <%= f.submit "Update", class: "button primary-button big-button" %>
  </div>
<% end %>

<script>
  $('.chosen-select').chosen({allow_single_deselect: true});
</script>

app/views/account_settings/_manage_subscription.html.erb
<div class="card mb-10 b-radius-0 b-none box-shadow-none">
  <h3>Subscription Details</h3>
  <% if @subscription && @corporate %>
    <%= render partial: 'subscription_corporate.html.erb',
                locals: { subscription: @subscription,
                          plan: @plan,
                          company_name: @company_name,
                          next_invoice: @next_invoice } %>
  <% elsif @subscription && @subscription.full? %>
    <%= render partial: 'subscription_info.html.erb',
                locals: { subscription: @subscription,
                          card: @card,
                          plan: @plan,
                          invoices: @invoices,
                          next_invoice: @next_invoice } %>
  <% elsif @subscription && @subscription.trial? %>
    <%= render partial: 'free_trial_subscription_info.html.erb',
                locals: { trial: @subscription } %>
  <% else %>
    <%= render partial: 'no_plan_subscription_info.html.erb' %>
  <% end %>
</div>

app/views/account_settings/_no_plan_subscription_info.html.erb
<label>Plan</label>
<p>None</p>

<div class="mt-30">
  <%= link_to "Sign Up", billing_info_account_settings_path, class: "button primary-button big-button" %>
</div>

app/views/account_settings/_payment_form.html.erb
<%= form_tag payment_route, { id: 'payment-form' } do %>
  <%= render partial: "account_settings/subscription_form" %>
  <% if !@card %>
    <div class="card mb-30 min-w-330">
      <h3>Payment Information</h3>
      <div class="form-row">
        <label for="card-element">
          Enter card details
        </label>
        <div id="card-element"></div>
        <div id="card-errors" style="color: #E4584C"></div>
      </div>
      <p></p>
      <button id="submit-cc-button" class="button primary-button big-button">Update</button>
    </div>
  <% else %>
    <button id="submit-cc-button" class="button primary-button big-button">Submit</button>
  <% end %>
<% end %>

<% if !@card %>
  <%= javascript_include_tag "https://js.stripe.com/v3/" %>
  <%= javascript_include_tag "stripe_elements_card" %>

  <script>
    setupStripeCardEntryForm('<%= Rails.configuration.stripe[:publishable_key] %>')
  </script>
<% end %>

app/views/account_settings/_subscription_info.html.erb
<label>Plan</label>
<p><%= plan.try(:name) || '--' %></p>

<label>Start Date</label>
<p><%= date_format(subscription.start_at) || '–' %></p>

<label>Next Invoice</label>
<% if @subscription_cancelled %>
  <p>Subscription was canceled. It will be available until <%= date_format @subscription_end_time %></p>
<% elsif next_invoice.present? %>
  <p><%= "$#{next_invoice.amount / 100.0} - #{date_format(next_invoice.date)} - Automatic Collection" %></p>
<% else %>
  <p>–</p>
<% end %>

<label>Billing Info</label>
<%= render partial: 'account_settings/stripe_card_information', locals: { card: card, update_payment_path: update_subscription_information_account_settings_path } %>

<h3>Previous Invoices</h3>
<%= render partial: 'account_settings/previous_invoices', locals: { invoices: invoices } %>

<div class="mt-20">
  <%= link_to "Update Subscription", billing_info_account_settings_path, class: "button primary-button big-button mt-10 inline-block fixed-width-big p-10" %>
  <% if !@subscription_cancelled %>
    <%= link_to "Cancel Subscription", cancel_subscription_account_settings_path, class: "button secondary-button big-button mt-10 inline-block fixed-width-big p-10" %>
  <% end %>
</div>

app/views/account_settings/_vault_co_owners.html.erb
<%= form_for @user_profile, :url => url_for(action: :update_vault_co_owner, controller: :account_settings) do |f| %>
  <div class="card mb-30 b-radius-0 b-none box-shadow-none">

    <div class="card shared-with b-radius-0 bl-none mb-0 mt-30">
      <h3 class="card-label">
        <svg class="icon" viewBox="0 0 20 20">
          <use xlink:href="#icon-Safe"></use>
        </svg>
        Vault Co-Owner
      </h3>
      <p class="shared-description">
        The contact(s) selected for 'Vault Co-Owner' have full read and write access to this ZokuVault account and all of its details. This person is typically a spouse, attorney or family member.</p>
      <%= f.label :primary_shared_with, 'Vault Co-Owner(s)' %>
      <div class="chosen-styled-select">
        <%= contact_select_with_create_new(f, :primary_shared_with_ids, @contacts_shareable, id: "primary_shared_with") %>
      </div>
    </div>
  </div>

  <div class="ml-15 mb-30">
    <%= f.submit "Update", class: "button primary-button big-button" %>
  </div>
<% end %>

<%= yield :new_contact_form %>

<script>
  $('.chosen-select').chosen({allow_single_deselect: true});
</script>

app/views/account_settings/_vault_inheritance.html.erb
<%= form_for @user_profile, :url => url_for(action: :update_vault_inheritance, controller: :account_settings) do |f| %>
  <div class="card mb-30 b-radius-0 b-none box-shadow-none">
    <% if @user_profile.errors.present? && (contact_error = @user_profile.errors.messages[:contact_validation_error]).present? %>
      <p class="error-label">The following contacts have invalid data. Please fix them and try again.</p>
      <ul class="mt-10">
        <% contact_error.flatten.each do |contact_error| %>
          <li class="error-label"><%= contact_error %></li>
        <% end %>
      </ul>
    <% end %>
    
    <h3>Vault Inheritance</h3>
    <p>Set up a chain of custody for your vault. If the following contact presents a valid death certificate to the ZokuVault team we will pass access of your account onto them. This role is primarily given to the executor of your will.</p>
    <%= f.label :full_primary_shared_with, 'Contingent Owner' %>
    <div class="chosen-styled-select mb-30">
      <%= contact_select_with_create_new(f, :full_primary_shared_with, @contacts_shareable, { id: "full_primary_shared_with", multiple: false }, [@user_profile.full_primary_shared_with.try(:id)]) %>
    </div>
    
    <div id="email-preview-list">
    </div>
  </div>

  <div class="ml-15 mb-30">
    <%= f.submit "Update", class: "button primary-button big-button" %>
  </div>
<% end %>

<%= yield :new_contact_form %>

<%= render partial: 'layouts/email_preview_javascript' %>

<div id="email-preview-section">
</div>

<script>
  $(document).ready(function() {
    setEmailPreviewSingleDropdown($('#full_primary_shared_with'))
    $('#full_primary_shared_with').trigger("change")
  })
  
  var displayEmailPreview = function(contact_id) {
    displayEmailPreviewVaultInheritance(contact_id)
  }
  
  $('.chosen-select').chosen({allow_single_deselect: true});
</script>

app/views/account_settings/billing_info.html.erb
<%= render partial: "account_settings/payment_form",
            locals: { payment_route: '/account_settings/update_payment' }
%>

app/views/account_settings/manage_subscription.html.erb
<%= content_for :current_tab_path, 'manage_subscription' %>
<%= render partial: 'account_settings' %>

app/views/account_settings/remove_corporate_access.html.erb
<div class="card">
  <h1>Remove Corporate Access</h1>
  
  <p>Removing corporate access severs all shared access between your account and <%= @corporate_admin.corporate_account_profile.business_name %>. This includes any employees, and all payment.</p>
  <p>Your account is currently paid through <%= date_format(@subscription.end_at) || '–' %></p>

  <%= link_to 'Remove Corporate Access', remove_corporate_access_update_account_settings_path(@corporate_admin_contact), method: :patch, class: 'button primary-button big-button inline-block mt-10 mb-10' %>
  <%= link_to 'Cancel', back_path || contacts_path, class: 'button secondary-button big-button inline-block mt-10 mb-10' %>
</div>

app/views/account_settings/thank_you_for_subscription.html.erb
<% if current_user.corporate_manager? %>
  <% description = "You have purchased a #{@plan_duration} subscription for #{@corporate_client.name}." %>
<% else %>
  <% description = "You have purchased a #{@plan_duration} subscription." %>
<% end %>

<div class="card max-w-1000-centered text-center">
  <h1 class="text-center">Thank You</h1>
  <p class="max-w-100-percent mb-20"><%= description %></p>
  <%= image_tag "marketing/rocket.png", :class => "block m-0-auto mb-20 w-30-percent"%>
  <%= link_to "Dashboard", root_path, class: 'button blue-button big-button inline-block' %>

  <% if current_user.corporate_manager? %>  
  <% else %>
    <%= link_to "Account Settings", manage_subscription_account_settings_path, class: 'button blue-button big-button inline-block' %>
  <% end %>
</div>

<%= render partial: 'layouts/improvely_conversion_tracking_js', locals: { goal: 'subscription payment', revenue: @revenue, reference: current_user.email } %>
<!‐‐ REFERSION TRACKING: BEGIN ‐‐>
<script src="//zokuvault.refersion.com/tracker/v3/pub_67c99ccb533535d2f230.js"></script>
<script>_refersion(function()
                   { _rfsn._setSource("STRIPE"); 
                    _rfsn._addCart("<%= @customer_id %>"); }
                  );
</script>
<!‐‐ REFERSION TRACKING: END ‐‐>

app/views/account_settings/vault_co_owners.html.erb
<%= content_for :current_tab_path, 'vault_co_owners' %>
<%= render partial: 'account_settings' %>

app/views/account_settings/vault_inheritance.html.erb
<%= content_for :current_tab_path, 'vault_inheritance' %>
<%= render partial: 'account_settings' %>