config/routes.rb
Rails.application.routes.draw do

  # always declare root path(s) first
  authenticated :user do
    root 'welcome#index', as: :authenticated_root
  end
  root to: 'high_voltage/pages#show', id: 'index'
  get '/index', to: redirect('/')

  resources :relationships
  resources :vendor_accounts
  resources :vendors
  devise_for :users, controllers: { registrations: 'registrations', confirmations: 'confirmations', passwords: 'passwords', sessions: 'sessions',
                                    unlocks: 'unlocks' }, :path => 'users', :path_names => { :sign_up => 'sign_up_form' }

  devise_scope :user do
    get 'users/password/create_new_invitation/:uuid', to: 'passwords#create_new_invitation', as: :create_new_password_invitation
    match 'active' => 'sessions#active', via: :get
    match 'timeout' => 'sessions#timeout', via: :get
  end

  scope 'insurance' do
    resources :lives, controller: :life_and_disabilities
    resources :properties, controller: :property_and_casualties
    resources :healths
  end

  delete 'insurance/properties/provider/:id' => 'property_and_casualties#destroy_provider'
  delete 'insurance/healths/provider/:id' => 'healths#destroy_provider'
  delete 'insurance/lives/provider/:id' => 'life_and_disabilities#destroy_provider'

  # Insurance Update All
  post 'insurance/lives/update_all' => 'life_and_disabilities#update_all'
  post 'insurance/healths/update_all' => 'healths#update_all'
  post 'insurance/properties/update_all' => 'property_and_casualties#update_all'

  # Mailer
  post 'contact_us', to: 'messages#create'
  post 'mailing_list', to: 'interested_users#create'
  post 'users/sign_up_form', as: :sign_up

  # Taxes
  resources :taxes
  post 'taxes/update_tax_preparers', to: 'taxes#update_tax_preparers', as: :tax_update_preparers
  
  # Final Wishes
  resources :final_wishes

  get 'files' => 'welcome#files'
  get 'cards' => 'welcome#cards'
  get 'cardcolumn' => 'welcome#cardcolumn'
  get 'thank_you' => 'welcome#thank_you'
  get 'email_confirmed' => 'welcome#email_confirmed'
  get 'password_link_expired(/:corporate)' => 'welcome#reset_password_expired', as: :password_link_expired
  get 'onboarding_back' => 'welcome#onboarding_back', as: :onboarding_back

  # Default category pages ?Could probably be done better programatically?
  get 'wills_powers_of_attorney' => 'categories#wills_powers_of_attorney'
  get 'trusts_entities' => 'categories#trusts_entities'
  get 'healthcare_choices' => 'categories#healthcare_choices'
  get 'insurance' => 'categories#insurance', as: 'insurance'
  get 'shared' => 'categories#shared'
  get 'shared_view' => 'categories#shared_view_dashboard'
  get 'web_accounts' => 'categories#web_accounts'

  resources :interested_users
  get 'mailing_list_confirm' => 'interested_users#mailing_list_confirm'

  resources :users, only: [:index, :destroy]

  # Wills
  get 'wills/new(/:shared_user_id)', to: 'wills#new', as: :new_will
  get 'wills/edit/:id(/:shared_user_id)', to: 'wills#edit', as: :edit_will
  get 'wills/show/:id(/:shared_user_id)', to: 'wills#show', as: :will
  patch 'wills/show/:id', to: 'wills#update'
  patch 'wills/:id', to: 'wills#update'
  get 'wills', to: 'wills#index', as: :wills
  post 'wills', to: 'wills#create'
  put 'wills', to: 'wills#update'
  delete 'wills/:id', to: 'wills#destroy'

  # Powers of Attorney
  get 'power_of_attorneys/new(/:shared_user_id)', to: 'power_of_attorneys#new', as: :new_power_of_attorney
  get 'power_of_attorneys/edit/:id(/:shared_user_id)', to: 'power_of_attorneys#edit', as: :edit_power_of_attorney
  get 'power_of_attorneys/show/:id(/:shared_user_id)', to: 'power_of_attorneys#show', as: :power_of_attorney
  patch 'power_of_attorneys/show/:id', to: 'power_of_attorneys#update'
  patch 'power_of_attorneys/:id', to: 'power_of_attorneys#update'
  get 'power_of_attorneys', to: 'power_of_attorneys#index', as: :power_of_attorneys
  post 'power_of_attorneys', to: 'power_of_attorneys#create'
  put 'power_of_attorneys', to: 'power_of_attorneys#update'
  delete 'power_of_attorneys/:id', to: 'power_of_attorneys#destroy'
  delete 'power_of_attorneys/powers_of_attorney_contact/:id', to: 'power_of_attorneys#destroy_power_of_attorney_contact', as: :delete_power_of_attorney
  get 'power_of_attorneys/new/get_powers_of_attorney_details', to: 'power_of_attorneys#get_powers_of_attorney_details'

  # Trusts
  get 'trusts/new(/:shared_user_id)', to: 'trusts#new', as: :new_trust
  get 'trusts/edit/:id(/:shared_user_id)', to: 'trusts#edit', as: :edit_trust
  get 'trusts/show/:id(/:shared_user_id)', to: 'trusts#show', as: :trust
  patch 'trusts/show/:id', to: 'trusts#update'
  patch 'trusts/:id', to: 'trusts#update'
  get 'trusts', to: 'trusts#index', as: :trusts
  post 'trusts', to: 'trusts#create'
  post 'trusts/update_all', to: 'trusts#update_all'
  put 'trusts', to: 'trusts#update'
  delete 'trusts/:id', to: 'trusts#destroy'

  # Entities
  get 'entities/new(/:shared_user_id)', to: 'entities#new', as: :new_entity
  get 'entities/:id/edit(/:shared_user_id)', to: 'entities#edit', as: :edit_entity
  patch 'entities/:id', to: 'entities#update'
  get 'entities/:id(/:shared_user_id)', to: 'entities#show', as: :entity
  post 'entities', to: 'entities#create', as: :entities
  post 'entities/update_all', to: 'entities#update_all'
  delete 'entities/:id', to: 'entities#destroy'

  resources :categories do
    member do
      post :share
      get :share_category
      delete 'share_category/:contact_id', to: 'categories#destroy_share_category'
    end
  end
  
  # Online Accounts
  get 'online_accounts/reveal_password/:account_id(/:shared_user_id)', to: 'online_accounts#reveal_password'
  get 'online_accounts', to: 'online_accounts#index', as: :online_accounts
  get 'online_accounts/new(/:shared_user_id)', to: 'online_accounts#new', as: :new_online_account
  get 'online_accounts/:id/edit(/:shared_user_id)', to: 'online_accounts#edit', as: :edit_online_account
  patch 'online_accounts/:id', to: 'online_accounts#update', as: :online_account
  post 'online_accounts', to: 'online_accounts#create'
  post 'online_accounts/update_all', to: 'online_accounts#update_all'
  delete 'online_accounts/:id', to: 'online_accounts#destroy'

  # Contacts
  get 'contacts/relationship_values/:contact_type(/:shared_user_id)', to: 'contacts#relationship_values'
  get 'contacts/new(/:shared_user_id)', to: 'contacts#new', as: :new_contact
  get 'contacts/:id(/:shared_user_id)', to: 'contacts#show', as: :contact
  get 'contacts/:id/edit(/:shared_user_id)', to: 'contacts#edit', as: :edit_contact
  resources :contacts, except: [:new, :edit, :show]

  # insurance details and create new account routes
  get 'insurance/:group/new_account', to: 'categories#new_account', as: :new_account_category
  get 'insurance/:group/details', to: 'categories#details_account', as: :details_account_category

  # Shares
  get 'shares' => 'shares#index'
  get 'shares/expired/:shared_user_id' => 'shares#shared_user_expired', as: :shared_user_expired

  # Documents
  get 'documents/get_drop_down_options/:category(/:shared_user_id)', to: 'documents#get_drop_down_options'
  get 'documents/get_card_names/:category(/:shared_user_id)', to: 'documents#get_card_names'
  get 'documents/document_category_share_contacts/:category(/:shared_user_id)', to: 'documents#document_category_share_contacts'
  get 'documents/document_subcategory_share_contacts/:category/:subcategory(/:shared_user_id)', to: 'documents#document_subcategory_share_contacts'
  get 'documents/', to: 'documents#index', as: :documents
  post 'documents/', to: 'documents#create'
  get 'documents/new(/:shared_user_id)', to: 'documents#new', as: :new_document
  get 'documents/edit/:uuid(/:shared_user_id)', to: 'documents#edit', as: :edit_document
  get 'documents/:uuid', to: 'documents#show', as: :document
  patch 'documents/:uuid', to: 'documents#update'
  delete 'documents/:uuid', to: 'documents#destroy'
  get 'documents/download/:uuid(/:shared_user_id)', to: 'documents#download', as: :download_document
  get 'documents/preview/:uuid(/:shared_user_id)', to: 'documents#preview', as: :preview_document
  get 'shared_view/:shared_user_id/documents/:uuid', to: 'documents#show', as: :shared_view_document
  post 'documents/mass_document_upload(/:shared_user_id)', to: 'documents#mass_document_upload', as: :mass_document_upload
  resources :documents, except: [:new, :edit], param: :uuid

  # Account Settings
  get 'account_settings', to: 'account_settings#index', as: :account_settings
  get 'account_settings/remove_corporate_access/:contact_id', to: 'account_settings#remove_corporate_access', as: :remove_corporate_access_account_settings
  get 'account_settings/remove_corporate_payment', to: 'account_settings#remove_corporate_payment', as: :remove_corporate_payment_account_settings
  get 'account_settings/vault_co_owners', to: 'account_settings#vault_co_owners', as: :vault_co_owners_account_settings
  get 'account_settings/login_settings', to: 'account_settings#login_settings', as: :login_settings_account_settings
  get 'account_settings/manage_subscription', to: 'account_settings#manage_subscription', as: :manage_subscription_account_settings
  get 'account_settings/vault_inheritance', to: 'account_settings#vault_inheritance', as: :vault_inheritance_account_settings
  get 'account_settings/phone_setup', to: 'account_settings#phone_setup', as: :phone_setup_account_settings
  put 'account_settings/phone_setup_update', to: 'account_settings#phone_setup_update', as: :phone_update_account_settings
  get 'account_settings/billing_info', to: 'account_settings#billing_info', as: :billing_info_account_settings
  get 'account_settings/cancel_subscription', to: 'account_settings#cancel_subscription', as: :cancel_subscription_account_settings
  get 'account_settings/invoice_information/:id', to: 'account_settings#invoice_information', as: :invoice_information_account_settings

app/models/power_of_attorney.rb
class PowerOfAttorney < ActiveRecord::Base
  include WtlBuildShares
  scope :for_user, ->(user) { where(user: user) }

  POWERS = %w(Digital Financial Healthcare General Limited Durable Springing)

  has_many :vault_entry_contacts, as: :contactable, dependent: :destroy
  has_many :shares, as: :shareable, dependent: :destroy

  belongs_to :category
  belongs_to :document
  belongs_to :user

  has_many :agents,
    -> { where("vault_entry_contacts.type = ? AND vault_entry_contacts.active = ?",
               VaultEntryContact.types[:power_of_attorney], true) },
  through: :vault_entry_contacts,
  source: :contact

  has_many :share_with_contacts, 
    through: :shares,
    source: :contact

  before_save { self.category = Category.fetch("wills - poa") }
  before_validation :build_shares
  
  def share_with_contact_ids
    @share_with_contact_ids || shares.map(&:contact_id)
  end

  attr_writer :share_with_contact_ids
  
  validates_length_of :notes, :maximum => ApplicationController.helpers.get_max_length(:notes)
  validates :agents, presence: { message: "Required" }
  validates :powers, presence: { message: "Required" }
end

app/views/power_of_attorneys/_form_wills_poa.html.erb
<div class="card attorney mb-30">

  <%= f.hidden_field :id, id: "attorney_id_#{index}" %>
  <% errors = data.try(:errors) %>
  
  <h3 class="card-label">Legal Details</h3>

  <label>Agent</label><span class="required">Required</span>
  <% if errors && errors.messages[:agents].present? %>
    <span class="error-label"> - <%= errors.messages[:agents].first %></span>
  <% end %>
  <div class="chosen-styled-select">
    <%= contact_select_with_create_new(f, :agent_ids, @contacts, id: "attorney_agent_id_#{index}", multiple: false, value: data && data.agent_ids) %>
  </div>

  <label>This Agent's powers are (please choose all that apply):</label>
  <% if errors && errors.messages[:powers].present? %>
    <span class="error-label"> - <%= errors.messages[:powers].first %></span>
  <% end %>
  <ul class="check-list">
    <% PowerOfAttorney::POWERS.each do |option| %>
      <li class="check-list">
        <label>
          <%= check_box_tag "power_of_attorney_contact[vault_entry_#{index}][powers][#{option}]",
            option,
            data && data.powers.try(:[], option), {:checked => data && data.powers.present? && data.powers.keys.any? {|check| check == option} }
          %>
        <span></span> <%= option %>
      </label>
      </li>
    <% end %>
  </ul>
  
  <%= f.label :notes %>
  <p><%= f.text_area :notes, id: "attorney_notes_id_#{index}", value: data && data.notes, :maxlength => get_max_length(:notes) %></p>

  <% if data && data.id && policy(data).destroy? %>
    <%= link_to 'Delete Agent', "#{yield(:delete_path)}#{data.id}", method: :delete,
        data: { confirm: "Deleting this '#{yield(:question_title)}' will permanently remove it from ZokuVault." },
        class: 'button small-button secondary-button', id: 'delete-legal' %>
  <% end %>

</div>

<script>
  clearForm = function($newWtlForm, old_id, new_id){
    new_vault_entry_id = "power_of_attorney_contact[vault_entry_" + new_id + "]";
    changeIdAndName($newWtlForm, "attorney_id_" + old_id,
      "attorney_id_" + new_id, new_vault_entry_id + "[id]");
    changeIdAndName($newWtlForm, "attorney_agent_id_" + old_id,
      "attorney_agent_id_" + new_id, new_vault_entry_id + "[agent_ids]");
    changeIdAndName($newWtlForm, "attorney_notes_id_" + old_id,
      "attorney_notes_id_" + new_id, new_vault_entry_id + "[notes]");
    changeIdAndName($newWtlForm, "attorney_share_id_" + old_id,
      "attorney_share_id_" + new_id, new_vault_entry_id + "[share_with_contact_ids][]");
    
    $newWtlForm.find(".check-list li").each(function() {
      var checkBox = $(this).find("input[type=checkbox]");
      checkBox.attr("name", "power_of_attorney_contact[vault_entry_" + new_id + "][powers][" + checkBox.attr('value') + "]")
      checkBox.attr("id", "power_of_attorney_contact_vault_entry_" + new_id + "_powers_" + checkBox.attr('value'))
      var checkBoxHidden = $(this).find("input[type=hidden]");
      checkBoxHidden.attr("name", "power_of_attorney_contact[vault_entry_" + new_id + "][powers][" + checkBox.attr('value') + "]")
      checkBoxHidden.attr("id", "power_of_attorney_contact_vault_entry_" + new_id + "_powers_" + checkBox.attr('value'))
    });
    
    $newWtlForm.find("#delete-legal").remove();
    $newWtlForm.find(".error-label").hide();
  }
</script>

app/views/power_of_attorneys/_new_document.html.erb
<%= render :partial => "layouts/bread_crumbs" %>

<h1><%= yield(:title) + ' - Setup' %></h1>
  <%= form_for(@power_of_attorney_contact, url: "#{yield(:url_path)}") do |f| %>
  <%= hidden_field_tag :shared_user_id, params[:shared_user_id] %>
  <% errors = @power_of_attorney_contact.errors %>

  <div class="card attorney mb-30">
    <%= f.label :contact_id, 'Power of Attorney For' %><span class="required">Required</span>
    <% if errors && errors.messages[:contact].present? %>
      <span class="error-label"> - <%= errors.messages[:contact].first %></span>
    <% end %>
    <div class="chosen-styled-select">
      <%= contact_select_with_create_new(f, :contact_id, @contacts, id: "power_of_attorney_for_id", multiple: false) %>
    </div>
  </div>

  <div id="wtl-forms">
    <div id="wtl-form-1">
      <% @power_of_attorney_contact.power_of_attorneys.each_with_index do |data, index| %>
        <%= f.fields_for "vault_entry_#{index}", data do |builder| %>
          <%= render yield(:partial_path), f: builder, index: index, data: data %>
        <% end %>
      <% end %>

      <% if @power_of_attorney_contact.power_of_attorneys.blank? %>
        <% index = 0 %>
        <%= f.fields_for "vault_entry_#{index}" do |builder| %>
          <%= render yield(:partial_path), f: builder, index: index, data: nil %>
        <% end %>
      <% end %>
    </div>
  </div>

  <% if yield(:add_another_title).present? %>
    <div class="add-new-button" href="" onclick="addNewField();">
      <svg class="icon add-icon">
        <use xlink:href="#icon-add-1"></use>
      </svg>
      Add another <%= yield(:add_another_title) %><br>
    </div>
  <% end %>

  
  <%= render partial: 'layouts/shared_with_email_preview_section', locals: { f: f, shared_with_field_symbol: :share_with_contact_ids,
                                                                             shared_with_dropdown_id: "power_attorney_shared_id",
                                                                             separate_shared_card: true,
                                                                             additional_params: { id: "power_attorney_shared_id" } } %>

  <%= render partial: 'layouts/save_cancel_buttons', locals: { previous_path: wills_powers_of_attorney_path, f: f } %>
  <% if @power_of_attorney_contact.try(:id) && policy(@power_of_attorney_contact).destroy? %>
    <%= link_to 'Delete Power of Attorney', delete_power_of_attorney_path(@power_of_attorney_contact), method: :delete,
        data: { confirm: "Deleting this 'Power of Attorney' will permanently remove it from ZokuVault." },
        class: 'big-button outline-button secondary-button fr', id: 'delete-legal' %>
  <% end %>
<% end %>

<script>
  clearFormFields = function(form){
    form.find(':text').val("");
    form.find('textarea').val("");
    form.find(':checked').prop('checked', false);
  }

  addNewField = function(){
    var $wtlForm = $('.card.attorney:last');
    var $newWtlForm = $wtlForm.clone();
    old_id_number = parseInt($wtlForm.find("input[type=hidden]").attr("id").split('_').last());
    new_id_number = old_id_number + 1;
    clearFormFields($newWtlForm);
    clearForm($newWtlForm, old_id_number, new_id_number);
    $('.chosen-container',$newWtlForm).remove();
    $newWtlForm.find(':text').val("");
    $newWtlForm.find(':checked').prop('checked', false);
    $newWtlForm.appendTo('#wtl-form-1');
    $('.chosen-select').chosen({allow_single_deselect: true});
    $('.chosen-container').css({"width": ""});//enforces > 0 width when adding policy in mobile view
  };
  $('.chosen-select').chosen({allow_single_deselect: true});
</script>

app/views/power_of_attorneys/edit.html.erb
<%= content_for :title, "Power of Attorney" %>
<%= content_for :question_title, "Agent" %>
<%= content_for :add_another_title, "agent" %>
<%= content_for :partial_path, "power_of_attorneys/form_wills_poa" %>
<%= content_for :url_path, "#{power_of_attorney_path(@power_of_attorney_contact)}" %>
<%= render partial: "new_document", locals: {:delete_button => true} %>
<%= yield :new_contact_form %>

app/views/power_of_attorneys/new.html.erb
<%= content_for :title, "Power of Attorney" %>
<%= content_for :question_title, "Agent" %>
<%= content_for :add_another_title, "agent" %>
<%= content_for :partial_path, "power_of_attorneys/form_wills_poa" %>
<%= content_for :url_path, power_of_attorneys_path %>
<%= content_for :delete_path, "/power_of_attorneys/" %>
<%= render partial: "new_document", locals: {:delete_button => false} %>
<%= yield :new_contact_form %>

app/views/power_of_attorneys/show.html.erb
<%= render :partial => "layouts/bread_crumbs" %>

<h1 class="card-title-220">Power of Attorney - <%= @power_of_attorney_contact.contact.try(:name) %></h1>
<%= link_to edit_power_of_attorney_path(@power_of_attorney_contact, @shared_user), class: "edit-link mrg-top" do%>
  <span class="circle-button">
    <svg class="icon circle-icon">
      <use xlink:href="#icon-pencil-1"></use>
    </svg>
  </span>Edit Power of Attorney
<% end %>

  <div class="card attorney mb-30">

    <% if @power_of_attorney_contact.power_of_attorneys.blank? %>
      <label>There is no information about this Power of Attorney</label>
    <% else %>
      <li class="data-pair b-none">
        <label>Agent</label><br>
        <span class="data-right">
          <label>Agent Powers</label><br>
        </span>
      </li>
    <% end %>
    
    <% @power_of_attorney_contact.power_of_attorneys.each do |power_of_attorney| %>
      <li class="data-pair">
        <p>
          <% if power_of_attorney.agents.present? %>
            <%= power_of_attorney.agents.map(&:name).join('') %>
          <% end %>
        </p>
        <span class="data-right">
          <% if power_of_attorney.powers.present? %>
            <% power_of_attorney.powers.keys.each do |agent_power| %>
              <%= agent_power %><br>
            <% end %>
          <% end %>
        </span>
      </li>
    <% end %>
    
    <section class="shared-with">
      <% if category_subcategory_shares(@power_of_attorney_contact, resource_owner).present? %>
        <h3 class="card-label shared-label">
          <svg class="icon" viewBox="0 0 20 20">
            <use xlink:href="#icon-Safe"></use>
          </svg> Shared With
        </h3>

        <label>Shared With</label>
        <div>
          <%= render :partial => "layouts/subcategory_share", :locals => { :shares => category_subcategory_shares(@power_of_attorney_contact, resource_owner) } %>
        </div>
      <% else %>
        <label> No share for this Power Of Attorney
      <% end %>
    </section>
  </div>

<h3>Documents</h3>
<a class="add-link fr" href="<%= new_document_path(:category => @power_of_attorney_contact.category.name, :card_document_id => CardDocument.power_of_attorney(@power_of_attorney_contact.id).id,
  :shared_user_id => @shared_user.present? ? @shared_user.id : "") %>">
  <span class="circle-button">
    <svg class="icon circle-icon">
      <use xlink:href="#icon-plus-1"></use>
    </svg>
  </span>Add Document
</a>

<%= render :partial => "layouts/standard_document_table", :locals => {:documents => @group_documents} %>