config/routes.rb
Rails.application.routes.draw do

  # always declare root path(s) first
  authenticated :user do
    root 'welcome#index', as: :authenticated_root
  end
  root to: 'high_voltage/pages#show', id: 'index'
  get '/index', to: redirect('/')

  resources :relationships
  resources :vendor_accounts
  resources :vendors
  devise_for :users, controllers: { registrations: 'registrations', confirmations: 'confirmations', passwords: 'passwords', sessions: 'sessions',
                                    unlocks: 'unlocks' }, :path => 'users', :path_names => { :sign_up => 'sign_up_form' }

  devise_scope :user do
    get 'users/password/create_new_invitation/:uuid', to: 'passwords#create_new_invitation', as: :create_new_password_invitation
    match 'active' => 'sessions#active', via: :get
    match 'timeout' => 'sessions#timeout', via: :get
  end

  scope 'insurance' do
    resources :lives, controller: :life_and_disabilities
    resources :properties, controller: :property_and_casualties
    resources :healths
  end

  delete 'insurance/properties/provider/:id' => 'property_and_casualties#destroy_provider'
  delete 'insurance/healths/provider/:id' => 'healths#destroy_provider'
  delete 'insurance/lives/provider/:id' => 'life_and_disabilities#destroy_provider'

  # Insurance Update All
  post 'insurance/lives/update_all' => 'life_and_disabilities#update_all'
  post 'insurance/healths/update_all' => 'healths#update_all'
  post 'insurance/properties/update_all' => 'property_and_casualties#update_all'

  # Mailer
  post 'contact_us', to: 'messages#create'
  post 'mailing_list', to: 'interested_users#create'
  post 'users/sign_up_form', as: :sign_up

  # Taxes
  resources :taxes
  post 'taxes/update_tax_preparers', to: 'taxes#update_tax_preparers', as: :tax_update_preparers
  
  # Final Wishes
  resources :final_wishes

  get 'files' => 'welcome#files'
  get 'cards' => 'welcome#cards'
  get 'cardcolumn' => 'welcome#cardcolumn'
  get 'thank_you' => 'welcome#thank_you'
  get 'email_confirmed' => 'welcome#email_confirmed'
  get 'password_link_expired(/:corporate)' => 'welcome#reset_password_expired', as: :password_link_expired
  get 'onboarding_back' => 'welcome#onboarding_back', as: :onboarding_back

  # Default category pages ?Could probably be done better programatically?
  get 'wills_powers_of_attorney' => 'categories#wills_powers_of_attorney'
  get 'trusts_entities' => 'categories#trusts_entities'
  get 'healthcare_choices' => 'categories#healthcare_choices'
  get 'insurance' => 'categories#insurance', as: 'insurance'
  get 'shared' => 'categories#shared'
  get 'shared_view' => 'categories#shared_view_dashboard'
  get 'web_accounts' => 'categories#web_accounts'

  resources :interested_users
  get 'mailing_list_confirm' => 'interested_users#mailing_list_confirm'

  resources :users, only: [:index, :destroy]

  # Wills
  get 'wills/new(/:shared_user_id)', to: 'wills#new', as: :new_will
  get 'wills/edit/:id(/:shared_user_id)', to: 'wills#edit', as: :edit_will
  get 'wills/show/:id(/:shared_user_id)', to: 'wills#show', as: :will
  patch 'wills/show/:id', to: 'wills#update'
  patch 'wills/:id', to: 'wills#update'
  get 'wills', to: 'wills#index', as: :wills
  post 'wills', to: 'wills#create'
  put 'wills', to: 'wills#update'
  delete 'wills/:id', to: 'wills#destroy'

  # Powers of Attorney
  get 'power_of_attorneys/new(/:shared_user_id)', to: 'power_of_attorneys#new', as: :new_power_of_attorney
  get 'power_of_attorneys/edit/:id(/:shared_user_id)', to: 'power_of_attorneys#edit', as: :edit_power_of_attorney
  get 'power_of_attorneys/show/:id(/:shared_user_id)', to: 'power_of_attorneys#show', as: :power_of_attorney
  patch 'power_of_attorneys/show/:id', to: 'power_of_attorneys#update'
  patch 'power_of_attorneys/:id', to: 'power_of_attorneys#update'
  get 'power_of_attorneys', to: 'power_of_attorneys#index', as: :power_of_attorneys
  post 'power_of_attorneys', to: 'power_of_attorneys#create'
  put 'power_of_attorneys', to: 'power_of_attorneys#update'
  delete 'power_of_attorneys/:id', to: 'power_of_attorneys#destroy'
  delete 'power_of_attorneys/powers_of_attorney_contact/:id', to: 'power_of_attorneys#destroy_power_of_attorney_contact', as: :delete_power_of_attorney
  get 'power_of_attorneys/new/get_powers_of_attorney_details', to: 'power_of_attorneys#get_powers_of_attorney_details'

  # Trusts
  get 'trusts/new(/:shared_user_id)', to: 'trusts#new', as: :new_trust
  get 'trusts/edit/:id(/:shared_user_id)', to: 'trusts#edit', as: :edit_trust
  get 'trusts/show/:id(/:shared_user_id)', to: 'trusts#show', as: :trust
  patch 'trusts/show/:id', to: 'trusts#update'
  patch 'trusts/:id', to: 'trusts#update'
  get 'trusts', to: 'trusts#index', as: :trusts
  post 'trusts', to: 'trusts#create'
  post 'trusts/update_all', to: 'trusts#update_all'
  put 'trusts', to: 'trusts#update'
  delete 'trusts/:id', to: 'trusts#destroy'

  # Entities
  get 'entities/new(/:shared_user_id)', to: 'entities#new', as: :new_entity
  get 'entities/:id/edit(/:shared_user_id)', to: 'entities#edit', as: :edit_entity
  patch 'entities/:id', to: 'entities#update'
  get 'entities/:id(/:shared_user_id)', to: 'entities#show', as: :entity
  post 'entities', to: 'entities#create', as: :entities
  post 'entities/update_all', to: 'entities#update_all'
  delete 'entities/:id', to: 'entities#destroy'

  resources :categories do
    member do
      post :share
      get :share_category
      delete 'share_category/:contact_id', to: 'categories#destroy_share_category'
    end
  end
  
  # Online Accounts
  get 'online_accounts/reveal_password/:account_id(/:shared_user_id)', to: 'online_accounts#reveal_password'
  get 'online_accounts', to: 'online_accounts#index', as: :online_accounts
  get 'online_accounts/new(/:shared_user_id)', to: 'online_accounts#new', as: :new_online_account
  get 'online_accounts/:id/edit(/:shared_user_id)', to: 'online_accounts#edit', as: :edit_online_account
  patch 'online_accounts/:id', to: 'online_accounts#update', as: :online_account
  post 'online_accounts', to: 'online_accounts#create'
  post 'online_accounts/update_all', to: 'online_accounts#update_all'
  delete 'online_accounts/:id', to: 'online_accounts#destroy'

  # Contacts
  get 'contacts/relationship_values/:contact_type(/:shared_user_id)', to: 'contacts#relationship_values'
  get 'contacts/new(/:shared_user_id)', to: 'contacts#new', as: :new_contact
  get 'contacts/:id(/:shared_user_id)', to: 'contacts#show', as: :contact
  get 'contacts/:id/edit(/:shared_user_id)', to: 'contacts#edit', as: :edit_contact
  resources :contacts, except: [:new, :edit, :show]

  # insurance details and create new account routes
  get 'insurance/:group/new_account', to: 'categories#new_account', as: :new_account_category
  get 'insurance/:group/details', to: 'categories#details_account', as: :details_account_category

  # Shares
  get 'shares' => 'shares#index'
  get 'shares/expired/:shared_user_id' => 'shares#shared_user_expired', as: :shared_user_expired

  # Documents
  get 'documents/get_drop_down_options/:category(/:shared_user_id)', to: 'documents#get_drop_down_options'
  get 'documents/get_card_names/:category(/:shared_user_id)', to: 'documents#get_card_names'
  get 'documents/document_category_share_contacts/:category(/:shared_user_id)', to: 'documents#document_category_share_contacts'
  get 'documents/document_subcategory_share_contacts/:category/:subcategory(/:shared_user_id)', to: 'documents#document_subcategory_share_contacts'
  get 'documents/', to: 'documents#index', as: :documents
  post 'documents/', to: 'documents#create'
  get 'documents/new(/:shared_user_id)', to: 'documents#new', as: :new_document
  get 'documents/edit/:uuid(/:shared_user_id)', to: 'documents#edit', as: :edit_document
  get 'documents/:uuid', to: 'documents#show', as: :document
  patch 'documents/:uuid', to: 'documents#update'
  delete 'documents/:uuid', to: 'documents#destroy'
  get 'documents/download/:uuid(/:shared_user_id)', to: 'documents#download', as: :download_document
  get 'documents/preview/:uuid(/:shared_user_id)', to: 'documents#preview', as: :preview_document
  get 'shared_view/:shared_user_id/documents/:uuid', to: 'documents#show', as: :shared_view_document
  post 'documents/mass_document_upload(/:shared_user_id)', to: 'documents#mass_document_upload', as: :mass_document_upload
  resources :documents, except: [:new, :edit], param: :uuid

  # Account Settings
  get 'account_settings', to: 'account_settings#index', as: :account_settings
  get 'account_settings/remove_corporate_access/:contact_id', to: 'account_settings#remove_corporate_access', as: :remove_corporate_access_account_settings
  get 'account_settings/remove_corporate_payment', to: 'account_settings#remove_corporate_payment', as: :remove_corporate_payment_account_settings
  get 'account_settings/vault_co_owners', to: 'account_settings#vault_co_owners', as: :vault_co_owners_account_settings
  get 'account_settings/login_settings', to: 'account_settings#login_settings', as: :login_settings_account_settings
  get 'account_settings/manage_subscription', to: 'account_settings#manage_subscription', as: :manage_subscription_account_settings
  get 'account_settings/vault_inheritance', to: 'account_settings#vault_inheritance', as: :vault_inheritance_account_settings
  get 'account_settings/phone_setup', to: 'account_settings#phone_setup', as: :phone_setup_account_settings
  put 'account_settings/phone_setup_update', to: 'account_settings#phone_setup_update', as: :phone_update_account_settings
  get 'account_settings/billing_info', to: 'account_settings#billing_info', as: :billing_info_account_settings
  get 'account_settings/cancel_subscription', to: 'account_settings#cancel_subscription', as: :cancel_subscription_account_settings
  get 'account_settings/invoice_information/:id', to: 'account_settings#invoice_information', as: :invoice_information_account_settings

app/models/interested_user.rb
class InterestedUser < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  
  validates :email, :email_format => { :message => "Email should contain @ and domain like .com" }
  validate :email_is_valid?
  
  private
  
  def email_is_valid?
    MailService.email_is_valid?(email, errors, :email)
  end
end

app/controllers/interested_users_controller.rb
class InterestedUsersController < ApplicationController
  before_action :check_privileges, only: [:index, :show, :edit, :update, :destroy]
  before_action :set_interested_user, only: [:show, :edit, :update, :destroy]

  # GET /interested_users
  # GET /interested_users.json
  def index
    @interested_users = InterestedUser.all
  end

  def mailing_list_confirm; end

  # GET /interested_users/1
  # GET /interested_users/1.json
  def show; end

  # GET /interested_users/1/edit
  def edit; end

  # POST /interested_users
  # POST /interested_users.json
  def create
    @interested_user = InterestedUser.new(interested_user_params)
    respond_to do |format|
      if @interested_user.save
        format.html { redirect_to mailing_list_confirm_path }
      else
        format.html { render 'pages/mailing-list' }
        format.json { render json: @interested_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interested_users/1
  # DELETE /interested_users/1.json
  def destroy
    @interested_user.destroy
    respond_to do |format|
      format.html { redirect_to interested_users_url, notice: 'User informtaion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_interested_user
    @interested_user = InterestedUser.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def interested_user_params
    params.require(:interested_user).permit(:name, :email, :phone_number, :message)
  end

  def check_privileges
    if user_exists_and_admin?
      true
    else
      redirect_to root_path
    end
  end

  def user_exists_and_admin?
    current_user && current_user.admin?
  end
end

app/helpers/interested_users_helper.rb
module InterestedUsersHelper
end

app/views/interested_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Interested In ZokuVault Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>Date Beta Submitted</th>
      <th>Message</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @interested_users.each do |interested_user| %>
      <tr>
        <td><%= interested_user.name %></td>
        <td><a><%= interested_user.email %></a></td>
        <td><%= interested_user.phone_number %></td>
        <td><%= date_format(interested_user.created_at) %></td>
        <td style="max-width: 400px; overflow: hidden; text-overflow: ellipsis;"><%= interested_user.message %></td>
        <td>
          <%= link_to 'Delete', interested_user, method: :delete, data: { confirm: 'Are you sure?' }, class: "outline-button small-button" %>
          <%= link_to 'Details', interested_user, class: "outline-button small-button" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/interested_users/mailing_list_confirm.html.erb
<% current_user = User.last %>
<button class="primary-button big-button hidden" data-modal-id="wizard-modal" id="show-modal-button">
  Wizard Modal
</button>
<div id="wizard-modal" class="modal wizard-modal modal-no-js confirmation-modal">
  <div class="confirmation-wrapper">
    <h3 class="confirmation-title">Thank You</h3>
    <p>Thank you for your interest in ZokuVault. We have received your information and will be in touch shortly.</p>
  </div>
  <footer class="modal-footer confirmation-footer">
    <%= link_to 'Close', mailing_list_page_path, class: "js-modal-close button secondary-button big-button", method: :get%>
  </footer>
</div>

<script>
$(function(){

  //SOMEONE PLEASE FIX THIS GARBAGE
  var appendthis =  ("<div class='modal-overlay js-modal-close'></div>");
  $(document).ready(function(){
    $('button[data-modal-id]').click();

    wizNav(1);
  });
  $('button[data-modal-id]').click(function(e) {
    e.preventDefault();
    $("body").append(appendthis);
    $(".modal-overlay").fadeTo(500, 0.8);
    $(".js-modalbox").fadeIn(500);
    var modalBox = $(this).attr('data-modal-id');
    $('#'+modalBox).fadeIn($(this).data());
  });

  $(".js-modal-close, .modal-overlay").click(function() {
    $(".modal, .modal-overlay").fadeOut(500, function() {
      $(".modal-overlay").remove();
    });

  });

  //ESPECIALLY THIS GARBAGE
  $(window).resize(function() {
    $(".large-modal").css({
      top: ($(window).height() - $(".modal").outerHeight()) / 2,
      left: ($(window).width() - $(".large-modal").outerWidth()) / 2,
    });
  });
  $(window).resize(function() {
    $(".medium-modal").css({
      top: ($(window).height() - $(".modal").outerHeight()) / 2,
      left: ($(window).width() - $(".medium-modal").outerWidth()) / 2,
    });
  });
  $(window).resize(function() {
    $(".small-modal").css({
      top: ($(window).height() - $(".modal").outerHeight()) / 2,
      left: ($(window).width() - $(".small-modal").outerWidth()) / 2,
    });
  });
  $(window).resize();
});
</script>

app/views/interested_users/show.html.erb
<p id="notice"><%= notice %></p>
<label>Name</label>
<p><%= @interested_user.name %></p>

<label>Phone</label>
<p><%= @interested_user.phone_number %></p>

<label>E-mail</label>
<p><%= @interested_user.email %></p>

<label>Message</label>
<p><%= @interested_user.message %></p>

<label>Date Beta Submitted</label>
<p><%= date_format(@interested_user.created_at) %></p>

<%= link_to 'Back', interested_users_path %>