config/routes.rb
Rails.application.routes.draw do

  # always declare root path(s) first
  authenticated :user do
    root 'welcome#index', as: :authenticated_root
  end
  root to: 'high_voltage/pages#show', id: 'index'
  get '/index', to: redirect('/')

  resources :relationships
  resources :vendor_accounts
  resources :vendors
  devise_for :users, controllers: { registrations: 'registrations', confirmations: 'confirmations', passwords: 'passwords', sessions: 'sessions',
                                    unlocks: 'unlocks' }, :path => 'users', :path_names => { :sign_up => 'sign_up_form' }

  devise_scope :user do
    get 'users/password/create_new_invitation/:uuid', to: 'passwords#create_new_invitation', as: :create_new_password_invitation
    match 'active' => 'sessions#active', via: :get
    match 'timeout' => 'sessions#timeout', via: :get
  end

  scope 'insurance' do
    resources :lives, controller: :life_and_disabilities
    resources :properties, controller: :property_and_casualties
    resources :healths
  end

  delete 'insurance/properties/provider/:id' => 'property_and_casualties#destroy_provider'
  delete 'insurance/healths/provider/:id' => 'healths#destroy_provider'
  delete 'insurance/lives/provider/:id' => 'life_and_disabilities#destroy_provider'

  # Insurance Update All
  post 'insurance/lives/update_all' => 'life_and_disabilities#update_all'
  post 'insurance/healths/update_all' => 'healths#update_all'
  post 'insurance/properties/update_all' => 'property_and_casualties#update_all'

  # Mailer
  post 'contact_us', to: 'messages#create'
  post 'mailing_list', to: 'interested_users#create'
  post 'users/sign_up_form', as: :sign_up

  # Taxes
  resources :taxes
  post 'taxes/update_tax_preparers', to: 'taxes#update_tax_preparers', as: :tax_update_preparers
  
  # Final Wishes
  resources :final_wishes

  get 'files' => 'welcome#files'
  get 'cards' => 'welcome#cards'
  get 'cardcolumn' => 'welcome#cardcolumn'
  get 'thank_you' => 'welcome#thank_you'
  get 'email_confirmed' => 'welcome#email_confirmed'
  get 'password_link_expired(/:corporate)' => 'welcome#reset_password_expired', as: :password_link_expired
  get 'onboarding_back' => 'welcome#onboarding_back', as: :onboarding_back

  # Default category pages ?Could probably be done better programatically?
  get 'wills_powers_of_attorney' => 'categories#wills_powers_of_attorney'
  get 'trusts_entities' => 'categories#trusts_entities'
  get 'healthcare_choices' => 'categories#healthcare_choices'
  get 'insurance' => 'categories#insurance', as: 'insurance'
  get 'shared' => 'categories#shared'
  get 'shared_view' => 'categories#shared_view_dashboard'
  get 'web_accounts' => 'categories#web_accounts'

  resources :interested_users
  get 'mailing_list_confirm' => 'interested_users#mailing_list_confirm'

  resources :users, only: [:index, :destroy]

  # Wills
  get 'wills/new(/:shared_user_id)', to: 'wills#new', as: :new_will
  get 'wills/edit/:id(/:shared_user_id)', to: 'wills#edit', as: :edit_will
  get 'wills/show/:id(/:shared_user_id)', to: 'wills#show', as: :will
  patch 'wills/show/:id', to: 'wills#update'
  patch 'wills/:id', to: 'wills#update'
  get 'wills', to: 'wills#index', as: :wills
  post 'wills', to: 'wills#create'
  put 'wills', to: 'wills#update'
  delete 'wills/:id', to: 'wills#destroy'

  # Powers of Attorney
  get 'power_of_attorneys/new(/:shared_user_id)', to: 'power_of_attorneys#new', as: :new_power_of_attorney
  get 'power_of_attorneys/edit/:id(/:shared_user_id)', to: 'power_of_attorneys#edit', as: :edit_power_of_attorney
  get 'power_of_attorneys/show/:id(/:shared_user_id)', to: 'power_of_attorneys#show', as: :power_of_attorney
  patch 'power_of_attorneys/show/:id', to: 'power_of_attorneys#update'
  patch 'power_of_attorneys/:id', to: 'power_of_attorneys#update'
  get 'power_of_attorneys', to: 'power_of_attorneys#index', as: :power_of_attorneys
  post 'power_of_attorneys', to: 'power_of_attorneys#create'
  put 'power_of_attorneys', to: 'power_of_attorneys#update'
  delete 'power_of_attorneys/:id', to: 'power_of_attorneys#destroy'
  delete 'power_of_attorneys/powers_of_attorney_contact/:id', to: 'power_of_attorneys#destroy_power_of_attorney_contact', as: :delete_power_of_attorney
  get 'power_of_attorneys/new/get_powers_of_attorney_details', to: 'power_of_attorneys#get_powers_of_attorney_details'

  # Trusts
  get 'trusts/new(/:shared_user_id)', to: 'trusts#new', as: :new_trust
  get 'trusts/edit/:id(/:shared_user_id)', to: 'trusts#edit', as: :edit_trust
  get 'trusts/show/:id(/:shared_user_id)', to: 'trusts#show', as: :trust
  patch 'trusts/show/:id', to: 'trusts#update'
  patch 'trusts/:id', to: 'trusts#update'
  get 'trusts', to: 'trusts#index', as: :trusts
  post 'trusts', to: 'trusts#create'
  post 'trusts/update_all', to: 'trusts#update_all'
  put 'trusts', to: 'trusts#update'
  delete 'trusts/:id', to: 'trusts#destroy'

  # Entities
  get 'entities/new(/:shared_user_id)', to: 'entities#new', as: :new_entity
  get 'entities/:id/edit(/:shared_user_id)', to: 'entities#edit', as: :edit_entity
  patch 'entities/:id', to: 'entities#update'
  get 'entities/:id(/:shared_user_id)', to: 'entities#show', as: :entity
  post 'entities', to: 'entities#create', as: :entities
  post 'entities/update_all', to: 'entities#update_all'
  delete 'entities/:id', to: 'entities#destroy'

  resources :categories do
    member do
      post :share
      get :share_category
      delete 'share_category/:contact_id', to: 'categories#destroy_share_category'
    end
  end
  
  # Online Accounts
  get 'online_accounts/reveal_password/:account_id(/:shared_user_id)', to: 'online_accounts#reveal_password'
  get 'online_accounts', to: 'online_accounts#index', as: :online_accounts
  get 'online_accounts/new(/:shared_user_id)', to: 'online_accounts#new', as: :new_online_account
  get 'online_accounts/:id/edit(/:shared_user_id)', to: 'online_accounts#edit', as: :edit_online_account
  patch 'online_accounts/:id', to: 'online_accounts#update', as: :online_account
  post 'online_accounts', to: 'online_accounts#create'
  post 'online_accounts/update_all', to: 'online_accounts#update_all'
  delete 'online_accounts/:id', to: 'online_accounts#destroy'

  # Contacts
  get 'contacts/relationship_values/:contact_type(/:shared_user_id)', to: 'contacts#relationship_values'
  get 'contacts/new(/:shared_user_id)', to: 'contacts#new', as: :new_contact
  get 'contacts/:id(/:shared_user_id)', to: 'contacts#show', as: :contact
  get 'contacts/:id/edit(/:shared_user_id)', to: 'contacts#edit', as: :edit_contact
  resources :contacts, except: [:new, :edit, :show]

  # insurance details and create new account routes
  get 'insurance/:group/new_account', to: 'categories#new_account', as: :new_account_category
  get 'insurance/:group/details', to: 'categories#details_account', as: :details_account_category

  # Shares
  get 'shares' => 'shares#index'
  get 'shares/expired/:shared_user_id' => 'shares#shared_user_expired', as: :shared_user_expired

  # Documents
  get 'documents/get_drop_down_options/:category(/:shared_user_id)', to: 'documents#get_drop_down_options'
  get 'documents/get_card_names/:category(/:shared_user_id)', to: 'documents#get_card_names'
  get 'documents/document_category_share_contacts/:category(/:shared_user_id)', to: 'documents#document_category_share_contacts'
  get 'documents/document_subcategory_share_contacts/:category/:subcategory(/:shared_user_id)', to: 'documents#document_subcategory_share_contacts'
  get 'documents/', to: 'documents#index', as: :documents
  post 'documents/', to: 'documents#create'
  get 'documents/new(/:shared_user_id)', to: 'documents#new', as: :new_document
  get 'documents/edit/:uuid(/:shared_user_id)', to: 'documents#edit', as: :edit_document
  get 'documents/:uuid', to: 'documents#show', as: :document
  patch 'documents/:uuid', to: 'documents#update'
  delete 'documents/:uuid', to: 'documents#destroy'
  get 'documents/download/:uuid(/:shared_user_id)', to: 'documents#download', as: :download_document
  get 'documents/preview/:uuid(/:shared_user_id)', to: 'documents#preview', as: :preview_document
  get 'shared_view/:shared_user_id/documents/:uuid', to: 'documents#show', as: :shared_view_document
  post 'documents/mass_document_upload(/:shared_user_id)', to: 'documents#mass_document_upload', as: :mass_document_upload
  resources :documents, except: [:new, :edit], param: :uuid

  # Account Settings
  get 'account_settings', to: 'account_settings#index', as: :account_settings
  get 'account_settings/remove_corporate_access/:contact_id', to: 'account_settings#remove_corporate_access', as: :remove_corporate_access_account_settings
  get 'account_settings/remove_corporate_payment', to: 'account_settings#remove_corporate_payment', as: :remove_corporate_payment_account_settings
  get 'account_settings/vault_co_owners', to: 'account_settings#vault_co_owners', as: :vault_co_owners_account_settings
  get 'account_settings/login_settings', to: 'account_settings#login_settings', as: :login_settings_account_settings
  get 'account_settings/manage_subscription', to: 'account_settings#manage_subscription', as: :manage_subscription_account_settings
  get 'account_settings/vault_inheritance', to: 'account_settings#vault_inheritance', as: :vault_inheritance_account_settings
  get 'account_settings/phone_setup', to: 'account_settings#phone_setup', as: :phone_setup_account_settings
  put 'account_settings/phone_setup_update', to: 'account_settings#phone_setup_update', as: :phone_update_account_settings
  get 'account_settings/billing_info', to: 'account_settings#billing_info', as: :billing_info_account_settings
  get 'account_settings/cancel_subscription', to: 'account_settings#cancel_subscription', as: :cancel_subscription_account_settings
  get 'account_settings/invoice_information/:id', to: 'account_settings#invoice_information', as: :invoice_information_account_settings

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :corporate_admins, class_name: 'CorporateAdminCategory', foreign_key: 'user_id', dependent: :destroy
  
  after_save { self.class.identity_map(:bust_cache) }
  after_destroy { self.class.identity_map(:bust_cache) }

  validates :name, presence: true, uniqueness: true

  def self.fetch(name)
    identity_map.fetch(name, nil)
  end

  def self.identity_map(bust_cache = false)
    @identity_map = nil if bust_cache
    @identity_map ||= all.map { |c| [c.name.downcase.freeze, c] }.to_h
  end
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  # Friendly Id
  extend FriendlyId
  friendly_id :friendly_id_slug
  
  def should_generate_new_friendly_id?
    name_changed? || slug.blank?
  end
  
  def friendly_id_slug
    [:name, :group]
  end
  
  scope :for_user, ->(user) {where(user: user)}

  belongs_to :category
  belongs_to :contact
  belongs_to :user

  has_many :shares, as: :shareable, dependent: :destroy
  has_many :share_with_contacts, through: :shares, source: :contact
  has_many :documents, class_name: "Document", foreign_key: :vendor_id, dependent: :nullify

  has_many :vendor_accounts, dependent: :destroy

  accepts_nested_attributes_for :vendor_accounts

  validates :name, presence: { :message => "Required" }

  after_initialize :initialize_category_and_group
  before_validation :build_shares

  def share_with_ids
    @share_with_ids || shares.map(&:id)
  end

  attr_writer :share_with_ids
  
  validates_length_of :name, :maximum => ApplicationController.helpers.get_max_length(:default)
  validates_length_of :webaddress, :maximum => (ApplicationController.helpers.get_max_length(:web) + ApplicationController.helpers.get_max_length(:web_prefix))
  validates_length_of :street_address_1, :maximum => ApplicationController.helpers.get_max_length(:default)
  validates_length_of :city, :maximum => ApplicationController.helpers.get_max_length(:default)
  validates_length_of :zip, :maximum => ApplicationController.helpers.get_max_length(:zipcode)
  
  validates_format_of :webaddress,
                      :with => Validation::WEB_ADDRESS_URL,
                      :message => "Please enter a valid url (starts with 'http://' or 'https://')",
                      :allow_blank => true

  private 

  def initialize_category_and_group
    # subclasses should initialize values
  end

  def build_shares
    if not_shared_mode?
      shares.clear
      share_with_ids.select(&:present?).each do |contact_id|
        shares.build(user_id: user_id, contact_id: contact_id)
      end
    end
  end
  
  def not_shared_mode?
    Thread.current[:current_user].present? && user.present? &&
      Thread.current[:current_user] == user
  end
  
  def self.healths
    self.where(type: 'Health')
  end

  def self.properties
    self.where(type: 'PropertyAndCasualty')
  end

  def self.lives
    self.where(type: 'LifeAndDisability')
  end
  
  validates :state, inclusion: { in:  States::STATES.map(&:last), allow_blank: true }
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def wills_poa_empty?(user = current_user)
    return false unless user.present?
    category_name = Category.fetch(Rails.application.config.x.WillsPoaCategory.downcase).name
    Will.for_user(user).blank? && PowerOfAttorney.for_user(user).blank? &&
      PowerOfAttorneyContact.for_user(user).blank? &&
      Document.for_user(user).where(category: category_name).blank? &&
      Contact.for_user(user).where(relationship: 'Attorney', contact_type: 'Advisor').blank?
  end

  def trusts_entities_empty?(user = current_user)
    return false unless user.present?
    category_name = Category.fetch(Rails.application.config.x.TrustsEntitiesCategory.downcase).name
    Trust.for_user(user).blank? && Entity.for_user(user).blank? &&
      Document.for_user(user).where(category: category_name).blank? &&
      Contact.for_user(user).where(relationship: 'Attorney', contact_type: 'Advisor').blank?
  end

  def insurance_empty?(user = current_user)
    return false unless user.present?
    category_name = Category.fetch(Rails.application.config.x.InsuranceCategory.downcase).name
    Vendor.for_user(user).blank? &&
      Document.for_user(user).where(category: category_name).blank? &&
      Contact.for_user(user).where(relationship: 'Insurance Agent / Broker', contact_type: 'Advisor').blank?
  end

  def financial_information_empty?(user = current_user)
    return false unless user.present?
    category_name = Category.fetch(Rails.application.config.x.FinancialInformationCategory.downcase).name
    FinancialAccountInformation.for_user(user).blank? &&
      FinancialInvestment.for_user(user).blank? &&
      FinancialAlternative.for_user(user).blank? &&
      FinancialProperty.for_user(user).blank? &&
      FinancialProvider.for_user(user).blank? &&
      Document.for_user(user).where(category: category_name).blank? &&
      Contact.for_user(user).where(relationship: 'Financial Advisor / Broker', contact_type: 'Advisor').blank?
  end

  def taxes_empty?(user = current_user)
    return false unless user.present?
    category_name = Category.fetch(Rails.application.config.x.TaxCategory.downcase).name
    Tax.for_user(user).blank? &&
      Document.for_user(user).where(category: category_name).blank? &&
      Contact.for_user(user).where(relationship: 'Accountant', contact_type: 'Advisor').blank?
  end
  
  def final_wishes_empty?(user = current_user)
    return false unless user.present?
    category_name = Category.fetch(Rails.application.config.x.FinalWishesCategory.downcase).name
    FinalWish.for_user(user).blank? &&
      Document.for_user(user).where(category: category_name).blank?
  end
  
  def online_accounts_empty?(user = current_user)
    return false unless user.present?
    category_name = Category.fetch(Rails.application.config.x.FinalWishesCategory.downcase).name
    OnlineAccount.for_user(user).blank?
  end
  
  def vault_inheritance_empty?(user = current_user)
    return false unless user.present? && user.user_profile.present?
    user.full_primary_shared_with.blank?
  end
  
  def vault_co_owner_empty?(user = current_user)
    return false unless user.present? && user.user_profile.present?
    user.primary_shared_with.blank?
  end
end

app/views/categories/_shared_category.html.erb
<% if !@shared_user.present? %>
  <% if category.present? %>
    <a class="edit-link fr" href='<%= share_category_category_path(category) %>'>
      <span class="circle-button">
        <svg class="icon circle-icon">
          <use xlink:href="#icon-pencil-1"></use>
        </svg>
      </span>Edit
    </a>
  <% end %>
  <h3>Shared With</h3>

  <div class="card category-shared">
    <section class="shared-with category-shared">
      <h3 class="card-label shared-label">
        <svg class="icon" viewBox="0 0 20 20">
          <use xlink:href="#icon-Safe"></use>
        </svg> Category Shared With
      </h3>

      <label>SHARED WITH</label>
      <div>
        <% if @contacts_with_access.blank? %>
          <p>No shared access</p>
        <% else %>
          <% @contacts_with_access.each do |contact| %>
            <% if contact.present? %>
              <%= render partial: "layouts/avatar_circle", locals: { :contact => contact } %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </section>
  </div>
<% end %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td>
          <a><%= link_to category.name, category %></a>
        </td>
        <td>
          <button class="outline-button small-button">
            <%= link_to 'Edit', edit_category_path(category) %>
          </button>
          <button class="outline-button small-button">
            <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %>
          </button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/insurance.html.erb
<% if (insurance_empty? && @shared_user.blank?) || @tutorial_in_progress %>
  <%= render partial: 'tutorials/category_empty_tutorial', locals: { next_tutorial_path: insurance_path(tutorial_in_progress: true) } %>
<% else %>
  <h1>Insurance</h1>

  <section class="flex-boxes">
    <% new_link_paths = {
    "life" => @shared_user.present? ? new_life_and_disability_shared_view_path : new_life_path,
    "property" => @shared_user.present? ? new_property_and_casualty_shared_view_path : new_property_path,
    "health" => @shared_user.present? ? new_health_shared_view_path : new_health_path,
    } %>

    <% @groups.each do |group| %>
      <div class="flex-column">
        <div class="card <%= group['value'] %> column-card section-header">
          <% count = insurance_document_count(resource_owner, group['value'], @category.name) %>
          <% if show_insurance_info?(resource_owner, @insurance_vendors, group['value']) %>
            <%= render :partial => "layouts/documents_count_icon", :locals => {:count => count } %>
            <h3 class="mb-20"><%= group["label"] %></h3>
          <% else %>
            <h3 class="mb-20"><%= group["label"] %></h3>
            <p>No shared items.</p>
          <% end %>
          <% if category_shared?(resource_owner, @category.name) %>
            <%= link_to 'Add Insurance', new_link_paths[group['value']], class: "small-button outline-button " %>
          <% end %>
          <span class="clear"></span>
        </div>

        <% if group['value']=="life" %>
          <% @insurance_vendors.select { |v| v["group"]=="life" }.each do |vendor| %>
            <div class="card <%= group['value'] %> column-card">

              <%= render :partial => "layouts/documents_count_icon", :locals => {:count => document_card_insurance_count(resource_owner, @category, group['label'], vendor.id) } %>
              <h3><%= vendor.name %></h3>

              <% vendor.try(:policy) && vendor.policy.each do |policy| %>
                <label><%= policy.policy_type %></label>
                <ul class="data-list">
                  <li class="data-pair">
                    <span class="pair-name">
                      <%= policy.policy_holder && policy.policy_holder.name %>
                    </span>
                    <span class="data-right">
                      <%= policy.coverage_amount && number_to_currency(policy.coverage_amount, unit: "$", precision: 0) %>
                    </span>
                  </li>
                </ul>
              <% end %>

              <% if provider_main_page_present?(vendor) %>
                <label>Provider Details</label>
                <ul class="data-list">
                  <li class="contact-pair">
                    <%if vendor.webaddress.present? %>
                      <%= link_to vendor.webaddress, vendor.webaddress, target: "_blank" %><br>
                    <% end %>
                    <%= vendor.phone %>
                  </li>
                </ul>
              <% end %>

              <% if category_subcategory_shares(vendor, resource_owner).present? %>
                <label>Shared With</label>
                <section class="shared-list">
                  <%= render :partial => "layouts/subcategory_share", :locals => { :shares => category_subcategory_shares(vendor, resource_owner) } %>
                </section>
              <% end %>

              <br>
              <%= link_to 'View Details', @shared_user.present? ? life_and_disability_shared_view_path(@shared_user, vendor) : life_path(vendor), class: "small-button outline-button mt-20" %>
            </div>
          <% end %>
        <% end %>

        <% if group['value']=="property" %>
          <% @insurance_vendors.select { |v| v["group"]=="property" }.each do |vendor| %>
            <div class="card <%= group['value'] %> column-card">

              <%= render :partial => "layouts/documents_count_icon", :locals => {:count => document_card_insurance_count(resource_owner, @category, group['label'], vendor.id) } %>
              <h3><%= vendor.name %></h3>

              <% vendor.try(:policy) && vendor.policy.each do |policy| %>
                <label><%= policy.policy_type %></label>
                <ul class="data-list">
                  <li class="data-pair">
                    <span class="pair-name">
                      <%= policy.insured_property %>
                    </span>
                    <span class="data-right">
                      <%= policy.coverage_amount && number_to_currency(policy.coverage_amount, unit: "$", precision: 0) %>
                    </span>
                  </li>
                </ul>
              <% end %>

              <% if provider_main_page_present?(vendor) %>
                <label>Provider Details</label>
                <ul class="data-list">
                  <li class="contact-pair">
                    <% if vendor.webaddress.present? %>
                      <%= link_to vendor.webaddress, vendor.webaddress, target: "_blank" %><br>
                    <% end %>
                    <%= vendor.phone %>
                  </li>
                </ul>
              <% end %>

              <% if category_subcategory_shares(vendor, resource_owner).present? %>
                <label>Shared With</label>
                <section class="shared-list">
                  <%= render :partial => "layouts/subcategory_share", :locals => { :shares => category_subcategory_shares(vendor, resource_owner) } %>
                </section>
              <% end %>

              <br>
              <%= link_to 'View Details', @shared_user.present? ? property_and_casualty_shared_view_path(@shared_user, vendor) : property_path(vendor), class: "small-button outline-button mt-20" %>
            </div>
          <% end %>
        <% end %>

        <% if group['value']=="health" %>
          <% @insurance_vendors.select { |v| v["group"]=="health" }.each do |vendor| %>
            <div class="card <%= group['value'] %> column-card">

              <%= render :partial => "layouts/documents_count_icon", :locals => {:count => document_card_insurance_count(resource_owner, @category, group['label'], vendor.id) } %>
              <h3><%= vendor.name %></h3>

                <% vendor.try(:policy) && vendor.policy.each do |policy| %>
                  <label><%= policy_type_abbreviate(policy.policy_type) %></label>
                  <ul class="data-list">
                    <li class="data-pair ">
                      <span class="pair-name"><%= policy.policy_holder && policy.policy_holder.name %></span>
                      <span class="data-right">
                        <%= policy.policy_number %>
                      </span>
                    </li>
                  </ul>
                <% end %>

                <% if provider_main_page_present?(vendor) %>
                  <label>Provider Details</label>
                  <ul class="data-list">
                    <li class="contact-pair">
                      <% if vendor.webaddress.present? %>
                        <%= link_to vendor.webaddress, vendor.webaddress, target: "_blank" %><br>
                      <% end %>
                      <%= vendor.phone %>
                    </li>
                  </ul>
                <% end %>

                <% if category_subcategory_shares(vendor, resource_owner).present? %>
                  <label>Shared With</label>
                  <section class="shared-list">
                    <%= render :partial => "layouts/subcategory_share", :locals => { :shares => category_subcategory_shares(vendor, resource_owner) } %>
                  </section>
                <% end %>

              <br>
              <%= link_to 'View Details', @shared_user.present? ? health_shared_view_path(@shared_user, vendor) : health_path(vendor), class: "small-button outline-button mt-20" %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </section>



  <%= render :partial => "layouts/add_document_button", :locals => {documents_path: new_document_path(:shared_user_id => @shared_user.present? ? @shared_user.id : "", :category => @category.name),
    documents_title: "Insurance Documents"} %>

  <%= render :partial => "layouts/standard_document_table", :locals => {:documents => @insurance_documents} %>

  <%= render :partial => "layouts/shared_category", :locals => { :category => Rails.application.config.x.InsuranceCategory.downcase } %>
<% end %>

<%= javascript_include_tag 'flex_boxes' %>
<script>
var is_safari = navigator.userAgent.indexOf('Safari') != -1 && navigator.userAgent.indexOf('Chrome') == -1;
if(!is_safari){
  $(function(){
    $('.flex-boxes').masonry({
      columnWidth: '.flex-column',
      gutter: 20,
      percentPosition: true,
      itemSelector: '.flex-column'
    });
  });
}
</script>

app/views/categories/share_category.html.erb
<%= render :partial => "layouts/bread_crumbs" %>
<% document_upload_access = @category.name.downcase.eql?(Rails.application.config.x.DocumentsCategory.downcase) %>

<h1>Edit - <%= document_upload_access ? 'Document Upload Shared With' : @category.name %></h1>

<%= form_for :shareable_category, url: share_category_path(@shareable_category.id) do |f| %>
  <div class="card cg-3 mb-30 fin-toggle" data-toggle="true">

<% if document_upload_access %>
  Allow contacts to securely upload documents directly into your Vault.
<% else %>
  Sharing your entire category with a Contact will enable them to view all category details. This will include all of the accounts, contacts, documents and data associated with the category.
<% end %>
    <%= render partial: 'layouts/shared_with_email_preview_section', locals: { f: f, shared_with_field_symbol: :share_with_contact_ids,
                                                                               shared_with_dropdown_id: "shareable_category_share_with_contact_ids",
                                                                               title: document_upload_access ? "Upload Shared With" : "Category Shared With",
                                                                               skip_edit_share_class: true } %>
    
    
  </div>

  <%= f.submit 'Save', class: "button primary-button big-button" %>
  <%= link_to 'Cancel', back_path || root_path, class: "button secondary-button big-button" %>
<% end %>

<script>
  $('.chosen-select').chosen({allow_single_deselect: true});
</script>
<%= yield :new_contact_form %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

<h1>Folders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @category.children.each do |folder| %>
    <tr>
      <td>
        <a><%= link_to folder.name, folder %></a>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Folder', new_folder_path(@category) %>